Repository avasachinbaijal/AvaTax-REST-V3-JS-SDK, pull requests merged in 2022-02, with the labels that each got.

#49 Update for 2.4.7.6
  README.md
  package.json
  src/api/AgeVerificationApi.js
  src/api/ShippingVerificationApi.js
  src/index.js
  src/model/AgeVerifyFailureCode.js
  src/model/AgeVerifyRequest.js
  src/model/AgeVerifyRequestAddress.js
  src/model/AgeVerifyResult.js
  src/model/ErrorDetails.js
  src/model/ErrorDetailsError.js
  src/model/ErrorDetailsErrorDetails.js
  src/model/ShippingVerifyResult.js
  src/model/ShippingVerifyResultLines.js
Labels: 2.4.7.6

#54 Update for 2.4.14-beta
  README.md
  package.json
  src/api/AgeVerificationApi.js
  src/api/ShippingVerificationApi.js
  src/index.js
  src/model/AgeVerifyFailureCode.js
  src/model/AgeVerifyRequest.js
  src/model/AgeVerifyRequestAddress.js
  src/model/AgeVerifyResult.js
  src/model/ErrorDetails.js
  src/model/ErrorDetailsError.js
  src/model/ErrorDetailsErrorDetails.js
  src/model/ShippingVerifyResult.js
  src/model/ShippingVerifyResultLines.js
Labels: 2.4.14-beta

#67 Update for 2.4.26
  README.md
  package.json
  src/api/AgeVerificationApi.js
  src/api/ShippingVerificationApi.js
  src/index.js
  src/model/AgeVerifyFailureCode.js
  src/model/AgeVerifyRequest.js
  src/model/AgeVerifyRequestAddress.js
  src/model/AgeVerifyResult.js
  src/model/ErrorDetails.js
  src/model/ErrorDetailsError.js
  src/model/ErrorDetailsErrorDetails.js
  src/model/ShippingVerifyResult.js
  src/model/ShippingVerifyResultLines.js
Labels: 2.4.26
